Clinic_MVC/Models/Appointment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Appointment
    {
        [Key]
        public int appointment_id { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "PatientName")]
        public string patient_name { get; set; }
        public Nullable<int> patient_age { get; set; }
        public string gender { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Contact")]
        public string contact_number { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Appointment Date")]
        public System.DateTime appointment_date { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Time")]
        public string time { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Doctor Name")]
        public string doctor_name { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Department")]
        public string department { get; set; }
    }
}

Clinic_MVC/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinic_MVC.Models;

namespace Clinic_MVC.Controllers
{
    public class AppointmentsController : Controller
    {
        
        private Clinic_DBEntities db = new Clinic_DBEntities();

        // GET: Appointments
        public ActionResult Index()
        {
            if(HomeController.isUser || HomeController.isHome)
                return HttpNotFound();
            return View(db.Appointments.ToList());
        }
        public ActionResult Admin()
        {
            if (HomeController.isUser || HomeController.isHome)
                return HttpNotFound();
            return View();
        }
        // GET: Appointments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // GET: Appointments/Create
        public ActionResult Create()
        {
            if (HomeController.isHome)
                return HttpNotFound();
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "appointment_id,patient_name,patient_age,gender,contact_number,appointment_date,time,doctor_name,department")] Appointment appointment,string defAction,string defController)
        {
            if (ModelState.IsValid)
            {
                db.Appointments.Add(appointment);
                db.SaveChanges();
                
                return RedirectToAction(defAction,defController);
            }

            return View(appointment);
        }

        // GET: Appointments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (HomeController.isUser || HomeController.isHome)
                return HttpNotFound();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "appointment_id,patient_name,patient_age,gender,contact_number,appointment_date,time,doctor_name,department")] Appointment appointment)
        {
            
            if (ModelState.IsValid)
            {
                db.Entry(appointment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(appointment);
        }

        // GET: Appointments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (HomeController.isUser || HomeController.isHome)
                return HttpNotFound();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Appointment appointment = db.Appointments.Find(id);
            db.Appointments.Remove(appointment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Login()
        { return View(); }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string username, string password)
        {
            if(username=="Admin" &&  password=="Admin@1234")
            {
                
                return RedirectToAction("Admin","Appointments");
            }
            else
            {
                
                ViewBag.Notification = "Wrong Username or Password";
                return View();
            }
            
        }
        public ActionResult Logout()
        {
            

            return RedirectToAction("Index", "Home");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Clinic_MVC/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinic_MVC.Models;

namespace Clinic_MVC.Controllers
{
    public class DoctorsController : Controller
    {
        private Clinic_DBEntities db = new Clinic_DBEntities();

        // GET: Doctors
        public ActionResult Index()

        {
            if (HomeController.isUser || HomeController.isHome)
                return HttpNotFound();
            return View(db.Doctors.ToList());
        }
        public ActionResult Doctor_list()
        {
            if (HomeController.isHome)
                return HttpNotFound();
            return View(db.Doctors.ToList());
        }
        // GET: Doctors/Details/5
        public ActionResult Details(int? id)
        {
            if (HomeController.isUser || HomeController.isHome)
                return HttpNotFound();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: Doctors/Create
        public ActionResult Create()
        {
            if (HomeController.isUser || HomeController.isHome)
                return HttpNotFound();
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Department,Name,Degrees,Contact,Day,Time,DocId")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }
         
       
        // GET: Doctors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (HomeController.isUser || HomeController.isHome)
                return HttpNotFound();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Department,Name,Degrees,Contact,Day,Time,DocId")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (HomeController.isUser || HomeController.isHome)
                return HttpNotFound();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Clinic_MVC/Views/Appointments/Admin.cshtml
@model Clinic_MVC.Models.Appointment

@{
    ViewBag.Title = "Admin";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link rel="stylesheet" href="~/CSS/admin.css" />


<body>
    <div class="nav">
        <div class="left logo">
            <img src="~/Images/logo2.jpg" />
        </div>
        <div class="middle">
            <h2>Happy Life Health Care Center </h2>
        </div>
        <div>
            <p style="color:yellow; margin-top:10px">@Html.ActionLink("Logout", "Logout", "Appointments", new { area = "" }, new { @class = "nav-link" })</p>
        </div>

    </div>
    <center><h2>Welcome To Admin Page</h2></center>
    <div class="menu">
        <div class="card" style="width: 18rem; height: 18rem;">
            <img class="card-img-top" src="~/Images/login_bg.jpg" alt="Card image cap">
            <div class="card-body">
                <p class="card-text"> Doctors Management </p>


                <a href="@Url.Action("Index", "Doctors")" class="btn btn-primary">View</a>

            </div>
        </div>
        <div class="card" style="width: 18rem; height: 18rem;">
            <img class="card-img-top" src="~/Images/calender.jpg" alt="Card image cap">
            <div class="card-body">
                <p class="card-text"> Appointments Management </p>

                <a href="@Url.Action("Index", "Appointments")" class="btn btn-primary">View</a>

            </div>
        </div>

    </div>
</body>

Clinic_MVC/Views/Appointments/Create.cshtml
@model Clinic_MVC.Models.Appointment

@{
    ViewBag.Title = "Create";
}
<link rel="stylesheet" href="~/CSS/register.css">



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
<center>
    <div class="form-horizontal">
        <center><h4>Appointment</h4></center>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.patient_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patient_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient_age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient_age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patient_age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contact_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contact_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contact_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.appointment_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.appointment_date, new { htmlAttributes = new { @class = "form-control",type="date" } })
                @Html.ValidationMessageFor(model => model.appointment_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.doctor_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.doctor_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.doctor_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
</center>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinic_MVC/Views/Appointments/Delete.cshtml
@model Clinic_MVC.Models.Appointment

@{
    ViewBag.Title = "Delete";
}
<link rel="stylesheet" href="~/CSS/delete.css">
@Html.ActionLink("Back to List", "Index")


<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <table class="dl-horizontal">
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.patient_name) </b ></td>
            <td>@Html.DisplayFor(model => model.patient_name)</td>
        </tr>

        <tr>
            <td><b>@Html.DisplayNameFor(model => model.patient_age) </b ></td>
            <td>@Html.DisplayFor(model => model.patient_age)</td>
        </tr>

        <tr>
            <td><b>@Html.DisplayNameFor(model => model.gender) </b ></td>
            <td>@Html.DisplayFor(model => model.gender)</td>
        </tr>
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.contact_number) </b ></td>
            <td>@Html.DisplayFor(model => model.contact_number)</td>
        </tr>
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.appointment_date) </b ></td>
            <td>@Html.DisplayFor(model => model.appointment_date)</td>
        </tr>
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.time) </b ></td>
            <td>@Html.DisplayFor(model => model.time)</td>
        </tr>

        <tr>
            <td><b>@Html.DisplayNameFor(model => model.doctor_name) </b ></td>
            <td>@Html.DisplayFor(model => model.doctor_name)</td>
        </tr>
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.department) </b ></td>
            <td>@Html.DisplayFor(model => model.department)</td>
        </tr>






    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <center><input type="submit" value="Delete" class="btn btn-default" /></center>

        </div>
    }
</div>

Clinic_MVC/Views/Appointments/Details.cshtml
@model Clinic_MVC.Models.Appointment

@{
    ViewBag.Title = "Details";
}
<link rel="stylesheet" href="~/CSS/delete.css">


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.appointment_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<div>
    
    <hr />
    <h2>Details</h2>
    <table class="dl-horizontal">
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.patient_name) </b ></td>
            <td>@Html.DisplayFor(model => model.patient_name)</td>
        </tr>

        <tr>
            <td><b>@Html.DisplayNameFor(model => model.patient_age) </b ></td>
            <td>@Html.DisplayFor(model => model.patient_age)</td>
        </tr>

        <tr>
            <td><b>@Html.DisplayNameFor(model => model.gender) </b ></td>
            <td>@Html.DisplayFor(model => model.gender)</td>
        </tr>
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.contact_number) </b ></td>
            <td>@Html.DisplayFor(model => model.contact_number)</td>
        </tr>
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.appointment_date) </b ></td>
            <td>@Html.DisplayFor(model => model.appointment_date)</td>
        </tr>
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.time) </b ></td>
            <td>@Html.DisplayFor(model => model.time)</td>
        </tr>

        <tr>
            <td><b>@Html.DisplayNameFor(model => model.doctor_name) </b ></td>
            <td>@Html.DisplayFor(model => model.doctor_name)</td>
        </tr>
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.department) </b ></td>
            <td>@Html.DisplayFor(model => model.department)</td>
        </tr>






    </table>
</div>

Clinic_MVC/Views/Appointments/Edit.cshtml
@model Clinic_MVC.Models.Appointment

@{
    ViewBag.Title = "Edit";
}
<link rel="stylesheet" href="~/CSS/register.css">

<center><h2>Edit</h2></center>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Appointment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.appointment_id)

        <div class="form-group">
            @Html.LabelFor(model => model.patient_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patient_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient_age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient_age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patient_age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contact_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contact_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contact_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.appointment_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.appointment_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.appointment_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.doctor_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.doctor_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.doctor_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinic_MVC/Views/Appointments/Index.cshtml
@model IEnumerable<Clinic_MVC.Models.Appointment>

@{
    ViewBag.Title = "Index";
}
<link rel="stylesheet" href="~/CSS/doctor.css" />


<div class="nav">
    <div class="left logo">
        <img src="~/Images/logo2.jpg" />
    </div>
    <div class="middle">
        <h2>Happy Life Health Care Center </h2>
    </div>
    <div>
        <p style="color:#fff; margin-top:10px">@Html.ActionLink("Logout", "Logout", "Appointments", new { area = "" }, new { @class = "nav-link" })</p>
    </div>
</div>
<a href="@Url.Action("Admin", "Appointments")" class="btn btn-primary">Back</a>

<div class="menu">
    @Html.ActionLink("Create New", "Create", null, new { area = "", defAction = "Index", defController = "Appointments" }, new { @class = "nav-link" })
    <div><h2>Appointments List</h2></div>
    <div><input type="search" data-table="table table-hover" id="myInput" onkeyup="myFunction()" placeholder="Search.."></div>
</div>
<table class="table table-hover" id="myTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.patient_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.patient_age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contact_number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.appointment_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.doctor_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.department)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.patient_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.patient_age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.contact_number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.appointment_date.ToString().Split(' ')[0])
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.doctor_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.department)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.appointment_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.appointment_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.appointment_id })
            </td>
        </tr>
    }

</table>
<script>
    function myFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td1 = tr[i].getElementsByTagName("td")[0];
            td2 = tr[i].getElementsByTagName("td")[3];
            if (td1 || td2) {
                txtValue1 = td1.textContent || td1.innerText;
                txtValue2 = td2.textContent || td2.innerText;
                if (txtValue1.toUpperCase().indexOf(filter) > -1 || txtValue2.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>

Clinic_MVC/Views/Appointments/Login.cshtml
@model Clinic_MVC.Models.Appointment

@{
    ViewBag.Title = "Login";
}
<link rel="stylesheet" href="~/CSS/login.css">
<div class="nav">
    <div class="left logo">
        <img src="~/Images/logo2.jpg" />
    </div>
    <div class="middle">
        <h2>Happy Life Health Care Center </h2>
    </div>
    <div></div>
</div>
<div>
    @*@Html.ActionLink("Back to List", "Index")*@
    <a href="~/Home/Index" class="btn btn-primary">Back to Home</a>
</div>
@using (Html.BeginForm("Login", "Appointments", FormMethod.Post))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <center>
        <h3>Admin Login</h3>
        <div class="form-group">
            <label>UserName</label>
            <div class="col-md-10">
                @Html.TextBox("username", null, new { @class = "form-control", autocomplete = "off" })
            </div>
        </div>

        <div class="form-group">
            <label>Password</label>
            <div class="col-md-10">
                @Html.Password("password", null, new { @class = "form-control", autocomplete = "off" })
            </div>
        </div>

        <button type="submit" class="btn btn-success">Login</button>
    </center>
</div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <label>@ViewBag.Notification</label>
        </div>
    </div>
    
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}